apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: developer-gitops

resources:
  - namespace.yaml
  - argocd-instance.yaml
  - developer-gitops-argocd-extended-clusterrole.yaml
  - developer-gitops-argocd-extended-clusterrolebinding.yaml