apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  argocd.argoproj.io/sync-wave: "1"

bases:
  - https://github.com/redhat-cop/gitops-catalog/compliance-operator/operator/overlays/release-0.1?ref=v0.6
  - https://github.com/pittar/ocp4-compliance-pbmm/manifests?ref=main
  - https://github.com/pittar/ocp4-compliance-pbmm/compliance-view/mainfests?ref=main
