apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: workload-monitoring

commonAnnotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

bases:
  - https://github.com/redhat-cop/gitops-catalog/grafana-operator/overlays/user-app
  - dashboards

resources:
  - namespace.yaml
  - grafana-operatorgroup.yaml

patchesJson6902:
  - target:
      version: v1alpha1
      group: integreatly.org
      kind: Grafana
      name: grafana
    path: patch-grafana-sar.yaml
  - target:
      version: v1
      group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: cluster-monitoring-view
    path: patch-cluster-monitoring-view.yaml

