apiVersion: v1
kind: Secret
metadata:
  name: gitea-creds
  annotations:
    tekton.dev/git-0: http://gitea.scm.svc.cluster.local
type: kubernetes.io/basic-auth
stringData:
  username: developer
  password: openshift