apiVersion: operator.tekton.dev/v1alpha1
kind: TektonChain
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"
  name: chain
spec:
  targetNamespace: openshift-pipelines