apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: cosign-secret-generator
spec:
  template:
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
          envFrom:
          - secretRef:
              name: cosign-password
          command:
            - /bin/bash
            - -c
            - |
              #!/usr/bin/env bash
              # Download cosign binary.

              COSIGN_VERSION="v1.11.1"

              cd ~/tmp
              curl -L -o cosign https://github.com/sigstore/cosign/releases/download/$COSIGN_VERSION/cosign-linux-amd64

              chmod 777 ~/tmp/cosign

              # echo "Switch to pipelines namespace"
              # oc project openshift-pipelines

              # Generate cosign key pair.
              echo "Generate Cosign secret."

              ./cosign \
                generate-key-pair \
                k8s://openshift-pipelines/signing-secrets \
                -d

              echo "Cosign secret generated."
          name: cosign-secret-generator
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      serviceAccount: cosign-generator
      serviceAccountName: cosign-generator