apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: devspace-coffeeshop
spec:
  applicationMenu:
    section: Developer Tools
    imageURL: https://github.com/pittar-demos/rosa-devops/raw/main/images/devspaces.svg
  location: ApplicationMenu
  text: Coffeeshop DevSpace
  href: https://devspaces.apps.cluster-sjlmb.sjlmb.sandbox1400.opentlc.com#http://gitea.scm.svc.cluster.local:3000/developer/coffeeshop/raw/branch/main/devfile.yaml
