kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

bases:
  - ../../../04-tenants/developer-gitops
  - ../../../04-tenants/production-gitops
  - ../../../04-tenants/superhero-battle/cicd
  - ../../../04-tenants/superhero-battle/dev
  - ../../../04-tenants/superhero-battle/test

resources:
  - tenants-project.yaml
