apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-admin
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: admin
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: superhero-battle-cicd
