apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-operators

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  argocd.argoproj.io/sync-wave: "22"

bases:
  - github.com/redhat-cop/gitops-catalog/web-terminal-operator/operator/overlays/fast?ref=main
