kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  name: production-gitops-argocd-extended-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: production-gitops-argocd-extended-clusterrole
subjects:
  - kind: ServiceAccount
    name: argocd-argocd-application-controller
    namespace: production-gitops